name: The First WorkFlow
  on: 
    push: 
      branshes:
        - main
  jobs:
    example job:
      run-on: ubuntu latest


      steps:
        - name: print a welcome message
          run: echo"welcome to the first workfloe in github action
        
