name: The First WorkFlow
  on: 
    push: 
      bransh:
        - main
  jobs:
    example job:
      run on: ubuntu latest


      steps:
        name: print a welcome message
        run: welcome to the first workfloe in github action
        
